#!/usr/bin/env zsh

alias ls="exa"
alias la="ls -a"
alias ember="./node_modules/.bin/ember"
alias git=hub
alias vim=nvim
alias v=nvim
alias cask="brew cask"
alias rn="react-native"

alias mv="mv -v"
alias rm="rm -i -v"
alias cp="cp -v"

alias mux="tmuxinator"
