#!/usr/bin/env zsh

alias cask="brew cask"
alias la="ls -a"
v() { if [ "$#" -eq 0 ]; then nvim .; else nvim "$@"; fi; }
alias vr=vimr
alias vim=nvim

alias mv="mv -v"
alias rm="rm -i -v"
alias cp="cp -v"

alias mux="tmuxinator"

if command -v eza &>/dev/null; then
  alias ls='eza -lh --group-directories-first --icons=auto'
fi

if command -v bat &>/dev/null; then
  alias cat="bat"
fi
