#!/usr/bin/env zsh

alias cask="brew cask"
alias ember="./node_modules/.bin/ember"
alias la="ls -a"
alias rn="react-native"
alias v=nvim
alias vr=vimr
alias vim=nvim

alias mv="mv -v"
alias rm="rm -i -v"
alias cp="cp -v"

alias mux="tmuxinator"

if [[ `uname -s` = "Darwin" ]]; then
  alias git=hub
  alias ls="exa"
  alias cat="bat"
fi
